context:
  name: seaweedfs
  version: "3.88"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
    sha256: e4297ba27cc03d5b7d40676915841aa7ba32f1bd47d48bf28d47ce7af1b4fb2d
    target_directory: src
  - url: https://gitlab.com/cznic/mathutil/-/raw/master/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    file_name: LICENSE-modernc-mathutil
  - url: https://gitlab.com/cznic/strutil/-/raw/master/LICENSE
    sha256: 0f594b710bedb0335b15155204150cb1aac98e76144b52b852b43ce6a65eaaad
    file_name: LICENSE-modernc-strutil
  - url: https://gitlab.com/cznic/b/-/raw/master/LICENSE
    sha256: 9d07736d504d4e0215e9e7c30a7363919a27de54bf2be330a4235769b3f4436c
    file_name: LICENSE-modernc-b

build:
  script:
    - cd src
    - go-licenses save ./weed --ignore modernc.org/mathutil --ignore modernc.org/strutil --ignore modernc.org/b --save_path ../library_licenses
    - if: win
      then: go build -v -o %LIBRARY_BIN%\weed.exe .\weed
      else: go build -v -o $PREFIX/bin/weed ./weed
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - weed help
      - weed version
  - package_contents:
      bin:
        - weed

about:
  homepage: https://seaweedfs.com
  summary: Fast distributed storage system
  description: |
    SeaweedFS is a fast distributed storage system for blobs, objects, files, and data lake, for billions of files! Blob store has O(1) disk seek, cloud tiering. Filer supports Cloud Drive, cross-DC active-active replication, Kubernetes, POSIX FUSE mount, S3 API, S3 Gateway, Hadoop, WebDAV, encryption, Erasure Coding.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/seaweedfs/seaweedfs
  documentation: https://seaweedfs.com

extra:
  recipe-maintainers:
    - pavelzw
