context:
  name: seaweedfs
  version: "4.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
    sha256: 7b20ba4cf047ee2076e0b7fe24ca8ea0c364180f5180321a2f596aadc9d8a9c0
    target_directory: src
  - url: https://gitlab.com/cznic/mathutil/-/raw/master/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    file_name: LICENSE-modernc-mathutil
  - url: https://gitlab.com/cznic/strutil/-/raw/master/LICENSE
    sha256: 0f594b710bedb0335b15155204150cb1aac98e76144b52b852b43ce6a65eaaad
    file_name: LICENSE-modernc-strutil
  - url: https://gitlab.com/cznic/b/-/raw/master/LICENSE
    sha256: 9d07736d504d4e0215e9e7c30a7363919a27de54bf2be330a4235769b3f4436c
    file_name: LICENSE-modernc-b
  - url: https://raw.githubusercontent.com/kurin/blazer/refs/heads/master/LICENSE
    sha256: e2851ee2c9388d5f19a5bed780dfdc16ec860909545b092a399d4ef73a81b7f7
    file_name: LICENSE-kurin-blazer
  - url: https://www.apache.org/licenses/LICENSE-2.0.txt
    sha256: 09e8a9bcec8067104652c168685ab0931e7868f9c8284b66f5ae6edae5f1130b
    file_name: LICENSE-kurin-blazer-2
  - url: https://raw.githubusercontent.com/jmespath/go-jmespath/refs/heads/master/LICENSE
    sha256: 09e8a9bcec8067104652c168685ab0931e7868f9c8284b66f5ae6edae5f1130b
    file_name: LICENSE-jmespath-go-jmespath
  - url: https://raw.githubusercontent.com/apache/thrift/refs/heads/master/LICENSE
    sha256: d315e6cdedc07c478de6992027bfb66f220886c6216fd7e9885ced30c3703646
    file_name: LICENSE-apache-thrift
  - url: https://raw.githubusercontent.com/google/flatbuffers/refs/heads/master/LICENSE
    sha256: 09e8a9bcec8067104652c168685ab0931e7868f9c8284b66f5ae6edae5f1130b
    file_name: LICENSE-google-flatbuffers
  - url: https://raw.githubusercontent.com/substrait-io/substrait/refs/heads/main/LICENSE
    sha256: 09e8a9bcec8067104652c168685ab0931e7868f9c8284b66f5ae6edae5f1130b
    file_name: LICENSE-substrait

build:
  script:
    - cd src
    - go-licenses save ./weed --ignore modernc.org/mathutil --ignore modernc.org/strutil --ignore modernc.org/b --ignore github.com/jmespath/go-jmespath --ignore github.com/kurin/blazer --ignore github.com/apache/thrift --ignore github.com/google/flatbuffers --ignore github.com/substrait-io/substrait-protobuf 
      --save_path ../library_licenses
    - if: win
      then: go build -v -o %LIBRARY_BIN%\weed.exe .\weed
      else: go build -v -o $PREFIX/bin/weed ./weed
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - weed help
      - weed version
  - package_contents:
      bin:
        - weed

about:
  homepage: https://seaweedfs.com
  summary: Fast distributed storage system
  description: |
    SeaweedFS is a fast distributed storage system for blobs, objects, files, and data lake, for billions of files! Blob store has O(1) disk seek, cloud tiering. Filer supports Cloud Drive, cross-DC active-active replication, Kubernetes, POSIX FUSE mount, S3 API, S3 Gateway, Hadoop, WebDAV, encryption, Erasure Coding.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE-modernc-mathutil
    - LICENSE-modernc-strutil
    - LICENSE-modernc-b
    - LICENSE-kurin-blazer
    - LICENSE-kurin-blazer-2
    - LICENSE-jmespath-go-jmespath
    - LICENSE-apache-thrift
    - LICENSE-google-flatbuffers
    - LICENSE-substrait
  repository: https://github.com/seaweedfs/seaweedfs
  documentation: https://seaweedfs.com

extra:
  recipe-maintainers:
    - pavelzw
